

INSERT INTO USERS (ID, EMAIL, `FULL_NAME`, PASSWORD) VALUES (-1, 'miguel@gmail.com', 'Miguel Amaral', '123456');
INSERT INTO USERS (ID, EMAIL, `FULL_NAME`, PASSWORD) VALUES (-2, 'homer@simpson.com', 'Homer', '456789');

INSERT INTO PHONES (ID, USER_ID, `AREA_CODE`, `NUMBER`, `TYPE`) VALUES (-1, -1, '81', '999998888', 'MOBILE');
INSERT INTO PHONES (ID, USER_ID, `AREA_CODE`, `NUMBER`, `TYPE`) VALUES (-2, -1, '81', '33334444', 'LANDLINE');